apiVersion: v1
kind: Service
metadata:
  name: rag-pipeline
spec:
  type: NodePort 
  selector:
    app: rag-pipeline
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      nodePort: {{ .Values.backend.nodePort }}