apiVersion: v1
kind: Service
metadata:
  name: streamlit
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: {{ .Values.frontend.nodePort }}