apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: {{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}
        imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
        resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
        ports:
        - containerPort: {{ .Values.proxy.service.targetPort }}
