apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: {{ .Values.namespace }}
  labels:
    app: proxy
spec:
  selector:
    app: proxy
  ports:
    - protocol: TCP
      port: {{ .Values.proxy.service.port }}
      targetPort: {{ .Values.proxy.service.targetPort }} 
      nodePort: {{ .Values.proxy.service.nodePort }}
  type: {{ .Values.proxy.service.type }}