services:
  jenkins:
    build: .
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ../Jenkinsfile:/var/jenkins_home/Jenkinsfile
    networks:
      - local-net
    privileged: true
  
  python:
    image: python:3.10-slim
    container_name: python
    restart: unless-stopped
    networks:
      - local-net
    volumes:
      - ../rag-pipeline:/rag-pipeline  # Mount project directory for tests
    command: tail -f /dev/null

networks:
  local-net:

volumes:
  jenkins_home: