apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: model-serving
spec:
  selector:
    app: mydeployment
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30081
  type: NodePort
