name: Build and Push Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RAG_IMAGE_NAME: 'rag-pipeline'
  STREAMLIT_IMAGE_NAME: 'streamlit-app'
  NGINX_IMAGE_NAME: 'nginx'
  DOCKER_REGISTRY: 'anhtran2611/llm-repo-dockerhub'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r rag-pipeline/requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH=rag-pipeline/src
          pytest --cov=rag-pipeline/src \
                 --cov-report=xml:rag-pipeline/coverage.xml \
                 --junitxml=rag-pipeline/test-reports/results.xml \
                 rag-pipeline/tests/

      - name: Check coverage
        run: |
          LINE_RATE=$(grep -m1 "line-rate" rag-pipeline/coverage.xml | sed -n 's/.*line-rate="\([^"]*\).*/\1/p')
          COVERAGE=$(echo "$LINE_RATE * 100" | bc)
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Code coverage too low: ${COVERAGE}%"
            exit 1
          else
            echo "Coverage is sufficient: ${COVERAGE}%"
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./rag-pipeline/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: llm-agent
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push RAG Pipeline image
        uses: docker/build-push-action@v4
        with:
          context: ./rag-pipeline
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}:rag-pipeline-${{ github.sha }}

      - name: Build and push Streamlit image
        uses: docker/build-push-action@v4
        with:
          context: ./streamlit
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}:streamlit-app-${{ github.sha }}

      - name: Build and push Nginx image
        uses: docker/build-push-action@v4
        with:
          context: ./nginx
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}:nginx-${{ github.sha }}


